version: '3'
services:
  redis7001:
    image: redis:6.2.7-bullseye
    volumes:
      - ./services/redis-cluster/7001/redis.conf:/usr/local/etc/redis/7001/redis.conf
      - ./data/redis-cluster/7001/:/data/7001/
    ports:
      - 7001:7001
      - 17001:17001
    command: redis-server /usr/local/etc/redis/7001/redis.conf
    environment:
      - TZ=Asia/Shanghai
  redis7002:
    image: redis:6.2.7-bullseye
    volumes:
      - ./services/redis-cluster/7002/redis.conf:/usr/local/etc/redis/7002/redis.conf
      - ./data/redis-cluster/7002/:/data/7002/
    ports:
      - 7002:7002
      - 17002:17002
    command: redis-server /usr/local/etc/redis/7002/redis.conf
    environment:
      - TZ=Asia/Shanghai
  redis7003:
    image: redis:6.2.7-bullseye
    volumes:
      - ./services/redis-cluster/7003/redis.conf:/usr/local/etc/redis/7003/redis.conf
      - ./data/redis-cluster/7003/:/data/7003/
    ports:
      - 7003:7003
      - 17003:17003
    command: redis-server /usr/local/etc/redis/7003/redis.conf
    environment:
      - TZ=Asia/Shanghai
  redis7004:
    image: redis:6.2.7-bullseye
    volumes:
      - ./services/redis-cluster/7004/redis.conf:/usr/local/etc/redis/7004/redis.conf
      - ./data/redis-cluster/7004/:/data/7004/
    ports:
      - 7004:7004
      - 17004:17004
    command: redis-server /usr/local/etc/redis/7004/redis.conf
    environment:
      - TZ=Asia/Shanghai
  redis7005:
    image: redis:6.2.7-bullseye
    volumes:
      - ./services/redis-cluster/7005/redis.conf:/usr/local/etc/redis/7005/redis.conf
      - ./data/redis-cluster/7005/:/data/7005/
    ports:
      - 7005:7005
      - 17005:17005
    command: redis-server /usr/local/etc/redis/7005/redis.conf
    environment:
      - TZ=Asia/Shanghai
  redis7006:
    image: redis:6.2.7-bullseye
    volumes:
      - ./services/redis-cluster/7006/redis.conf:/usr/local/etc/redis/7006/redis.conf
      - ./data/redis-cluster/7006/:/data/7006/
    ports:
      - 7006:7006
      - 17006:17006
    command: redis-server /usr/local/etc/redis/7006/redis.conf
    environment:
      - TZ=Asia/Shanghai
